### ISSUE TITLE
Feat: SCA version release roadmap

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3502]
## Background
There have been a large number of requirements for version releases and bugfixes in recent community issues. This issue organizes the release requirements for each maintenance version. Everyone is welcome to claim and contribute!

The tentative main line of tasks is as follows:
- 2021.x and 2.2.x are mainly bugfixes;
- 2022.x mainly focuses on adapting new functional components.

## Todo
- [ ] Investigate the latest version of each component and adapt to sca 2022.x;
- [ ] Collect 2021.x bug issues;
- [ ] Collect 2.2.x bug issues.

**Comment by yuluo-yx** [comment]
## 2022.x components version (As of 2023.11.22) :
| component| last version                                                 | current version |is|status|
|--------| ------------------------------------------------------------ | --------------- |---|----|
| nacos | [2.2.3](https://github.com/alibaba/nacos/releases/tag/2.2.3) | 2.2.1           |yes| down|
| seata | [1.8.0](https://github.com/seata/seata/releases/tag/v1.8.0) | 1.7.0           |yes| down |
| rocketmq | [5.1.4](https://github.com/apache/rocketmq/releases/tag/rocketmq-all-5.1.4) | 4.9.4|yes| - |
| sentinel | [1.8.6](https://github.com/alibaba/Sentinel/releases/tag/1.8.6) | 1.8.6           |no| - |
| spring boot | [3.2.0](https://spring.io/projects/spring-boot#learn) | 3.0.2           |yes| - |
| spring cloud | [2023.0.0](https://spring.io/projects/spring-cloud#learn) | 2022.0.0   |yes| - |

spring boot and spring cloud: https://github.com/alibaba/spring-cloud-alibaba/pull/3528

**Comment by yuluo-yx** [comment]
Spring Cloud Alibaba 2021.x
- https://github.com/alibaba/spring-cloud-alibaba/issues/3476 
- https://github.com/alibaba/spring-cloud-alibaba/issues/3445 
- https://github.com/alibaba/spring-cloud-alibaba/issues/3496 
- https://github.com/alibaba/spring-cloud-alibaba/issues/3314
- https://github.com/alibaba/spring-cloud-alibaba/issues/3536
- https://github.com/alibaba/spring-cloud-alibaba/issues/3518
- https://github.com/alibaba/spring-cloud-alibaba/issues/3523 down

Spring Cloud Alibaba 2.2.x
- https://github.com/alibaba/spring-cloud-alibaba/issues/3322
- https://github.com/alibaba/spring-cloud-alibaba/issues/3535

**Comment by chickenlj** [comment]
> The tentative main line of tasks is as follows:
> 
> * 2021.x and 2.2.x are mainly bugfixes;
> * 2022.x mainly focuses on adapting new functional components.

Well done. I am interested in these two plans and would like to contribute.

**Comment by jaimyjie** [comment]
nacos2.2.3引用的tomcat包有中等级别漏洞，其2.3.0已经修复了，建议适配到2.3.0吧

**Comment by yuluo-yx** [comment]
> nacos2.2.3引用的tomcat包有中等级别漏洞，其2.3.0已经修复了，建议适配到2.3.0吧

好，这块社区最近正在做，如果有想法的话，欢迎参与进来

**Comment by yuluo-yx** [comment]
https://github.com/alibaba/spring-cloud-alibaba/issues/3593#issuecomment-1893205260
