### ISSUE TITLE
Bug: nacos related examples need to be updated,

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3546]
**Which Component**

spring-cloud-alibaba-nacos-example

## bgc

Because authentication is added in nacos 2.0.x version. Therefore, when using nacos server version 2.0.x or above in sca, you need to configure the user name and password before it can be used normally.

But 2021.x and 2022.x none of the examples in .x are configured.

## eg

https://github.com/alibaba/spring-cloud-alibaba/blob/93e4f7dd65c30287642156e61c9b56cf98db744d/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/src/main/resources/application.yaml#L10C1-L10C1

## ref
https://nacos.io/zh-cn/docs/auth.html
https://nacos.io/zh-cn/docs/v2/guide/user/auth.html
https://github.com/alibaba/spring-cloud-alibaba/pull/3537

## todo
- [x] Updated readme in 2021.x nacos example
- [x] Documentation instructions for configuring authentication when using nacos server version greater than 2.0.x
- [x] Change related configurations in nacos example

**Comment by yuluo-yx** [comment]
pls assign to me, I will to do it.

**Comment by yuluo-yx** [comment]
completed, closed now!
